/*
 * APIMATICCalculatorTestcases.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/07/2016
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using NUnit.Framework;
using APIMATICCalculatorTestcases.PCL;
using APIMATICCalculatorTestcases.PCL.Controllers;
 
using APIMATICCalculatorTestcases.PCL.Models;
 
using APIMATICCalculatorTestcases.PCL.Exceptions;
using APIMATICCalculatorTestcases.PCL.Http.Client;
using APIMATICCalculatorTestcases.Tests.Helpers;

namespace APIMATICCalculatorTestcases.Tests
{
    [TestFixture]
    public class SimpleCalculatorControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static SimpleCalculatorController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().SimpleCalculator;
        }

        /// <summary>
        /// Simply add two number together
        /// </summary>
        [Test]
        public async Task TestCheckSum() 
        {
            // Parameters for the API call
            GetCalculateInput input = new GetCalculateInput();
            input.Operation = "SUM";
            input.X = 5;
            input.Y = 5;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.GetCalculateAsync(input);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("10.0", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

    }
}
