/*
 * APIMATICCalculatorTestcases.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/08/2016
 */
using System;

namespace APIMATICCalculatorTestcases.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "http://examples.apimatic.io/apps/calculator";

        //The username to use with basic authentication
        //TODO: Replace the BasicAuthUserName with an appropriate value
        public static string BasicAuthUserName = "TODO: Replace";

        //The password to use with basic authentication
        //TODO: Replace the BasicAuthPassword with an appropriate value
        public static string BasicAuthPassword = "TODO: Replace";

    }
}